# Etapa 1: Build
FROM maven:3.9.6-eclipse-temurin-21 AS builder

WORKDIR /build

COPY app/pom.xml .

COPY app/src ./src

RUN mvn package -DskipTests

# Etapa 2: Runtime minimalista
FROM eclipse-temurin:21-jre-alpine

WORKDIR /app

COPY --from=builder /build/target/java-docker-1.0.jar app.jar

RUN addgroup -S appgroup && adduser -S java-docker -G appgroup
USER java-docker

CMD ["java", "-jar", "app.jar"]
